[attractions.sd-zoo]
name = "San Diego Zoo"
logo = "https://farm66.staticflickr.com/65535/buddyicons/52070776@N06_r.jpg"
description = "San Diego's world famous zoo houses 4,000 animals from more than 650 species. It is located in beautiful Balboa Park."
website = "https://zoo.sandiegozoo.org/"
address = "2920 Zoo Drive, San Diego, CA 92101"
hours_url = "https://zoo.sandiegozoo.org/plan-your-visit#hours"
parking = "Parking is free in the lot in front of the Zoo. Additional free parking is available throughout Balboa Park."
parking_url = "https://zoo.sandiegozoo.org/plan-your-visit#directions"

[attractions.safari-park]
name = "San Diego Zoo Safari Park"
logo = "https://farm66.staticflickr.com/65535/buddyicons/52070776@N06_r.jpg"
description = "One of San Diego's largest tourist attractions, the Safari Park houses a large array of wild and endangered animals from every continent."
website = "https://sdzsafaripark.org/"
address = "15500 San Pasqual Valley Road, Escondido, CA 92027-7017"
hours_url = "https://sdzsafaripark.org/visit#hours"
parking = "General parking (automobiles and motorcycles): $20 per vehicle. RV parking: starting at $38. Preferred parking: starting at $38. First come, first served; there are no in and out privileges."
parking_url = "https://sdzsafaripark.org/plan-your-visit#directions"

[attractions.birch]
name = "Birch Aquarium"
logo = "https://yt3.googleusercontent.com/ytc/AIdro_kZ12KhtAnQVIuF0gFHgriVrVU56bGtHEKHZ1uqU9oNK8A=s176-c-k-c0x00ffffff-no-rj?.jpg"
description = "Perched on a bluff overlooking the Pacific Ocean, Birch Aquarium at Scripps is the public exploration center for Scripps Institution of Oceanography at UC San Diego, featuring conservation breeding programs and interactive exhibits."
website = "https://aquarium.ucsd.edu/"
address = "2300 Expedition Way, La Jolla, CA 92037"
hours_url = "https://aquarium.ucsd.edu/daily-schedule/"
parking = "Free 3 hour parking. Full day permits available.
parking_url = "https://aquarium.ucsd.edu/plan-your-visit"

[attractions.leo-carillo]
name = "Leo Carillo Ranch"
description = "The personal retreat of 50s character actor Leo Carillo, featuring 27 acres of antique architecture, native plants and dozens of peacocks."
website = "http://carrillo-ranch.org/"
address = "6200 Flying Leo Carrillo Ln, Carlsbad, CA 92009"
hours = "9 AM to 5 PM daily"
parking = "General parking is available."

[attractions.childrens-pool]
name = "Children's Pool"
description = "The Children's Pool is a small beach in La Jolla partially protected by a seawall. Seals and sea lions visit the beach year-round."
website = "https://www.sandiego.gov/lifeguards/beaches/pool"
address = "850 Coast Blvd, La Jolla, CA 92037-4254"
parking = "Parking is limited to nearby streets."

[attractions.whiskers-wine]
name = "Whiskers and Wine Cat Lounge"
logo = "https://images.squarespace-cdn.com/content/v1/59b5afe6cf81e016621da57a/6aec34d1-1435-42fe-95a9-d8b094f96218/Signature+Logo+1000x1000+px.png"
description = "San Diego's only liquor-licensed cat café lounge gives guests the chance to spend time with some kitties, eat, drink and relax. [Cat yoga](https://www.whiskersandwinebar.com/cat-yoga) available on weekends. Limited to 14 people inside the venue at a time."
website = "https://www.whiskersandwinebar.com/"
address = "2856 Adams Ave., San Diego, CA 92116"

[attractions.la-jolla-shores]
name = "La Jolla Shores Beach"
description = "Swim with leopard sharks during the summer, or see other local ocean wildlife through snorkel tours."
website = "https://www.sandiego.org/explore/things-to-do/beaches-bays/la-jolla.aspx"
address = "8277 Camino Del Oro, La Jolla, CA 92037"
parking = "Free public parking. First come, first served."

